/**
 * MongoDB credentials
 * You may add connection string for production environment
 */

module.exports = {
  mongo: {
    development: {
      connectionString: 'mongodb://localhost:27017/auth'
    }
  }
};

/**
 * CLOUD9 users
 * Please use the connection string generated byte
 * MongoLab environment
 * Do NOT use the above localhost string!!
 */